(function (root, factory) {
  if (typeof module === 'object' && module.exports) {
    module.exports = factory();
  } else {
    root.CurlExtensionRequestContext = factory();
  }
})(typeof globalThis === 'object' ? globalThis : this, function () {
  'use strict';

  // These fields belong to the browser's transport and must be regenerated by
  // curl.  In particular, forwarding Accept-Encoding would make curl write a
  // compressed response to the destination file instead of the decoded body.
  const BLOCKED_HEADERS = new Set([
    'host',
    'content-length',
    'connection',
    'proxy-authorization',
    'range',
    'if-range',
    'accept-encoding',
    'keep-alive',
    'proxy-connection',
    'transfer-encoding',
    'te',
    'trailer',
    'upgrade'
  ]);
  const TOKEN_PATTERN = /^[!#$%&'*+\-.^_`|~0-9A-Za-z]+$/;
  const MAX_HEADER_COUNT = 64;
  const MAX_HEADER_VALUE_BYTES = 8 * 1024;
  const MAX_CONTEXT_BYTES = 48 * 1024;

  function byteLength(value) {
    return new TextEncoder().encode(String(value)).length;
  }

  function invalidHeader(message) {
    throw new Error(`Invalid request header: ${message}`);
  }

  function validateHeader(name, value) {
    const normalizedName = String(name || '').trim();
    if (!TOKEN_PATTERN.test(normalizedName)) invalidHeader('name');
    const normalizedValue = String(value === undefined || value === null ? '' : value);
    if (/[\r\n\0]/.test(normalizedValue)) invalidHeader('value');
    if (byteLength(normalizedValue) > MAX_HEADER_VALUE_BYTES) {
      throw new Error('Request header value is too large');
    }
    return { name: normalizedName, value: normalizedValue };
  }

  function filterRequestHeaders(requestHeaders) {
    if (requestHeaders === undefined || requestHeaders === null) return [];
    if (!Array.isArray(requestHeaders)) invalidHeader('list');
    if (requestHeaders.length > MAX_HEADER_COUNT) {
      throw new Error('Too many request headers');
    }
    const filtered = [];
    let totalBytes = 0;
    for (const header of requestHeaders) {
      if (!header || typeof header !== 'object') invalidHeader('entry');
      const normalized = validateHeader(header.name, header.value);
      if (BLOCKED_HEADERS.has(normalized.name.toLowerCase())) continue;
      totalBytes += byteLength(normalized.name) + byteLength(normalized.value);
      if (totalBytes > MAX_CONTEXT_BYTES) {
        throw new Error('Request header context is too large');
      }
      filtered.push(normalized);
    }
    return filtered;
  }

  function supportedUrl(value) {
    try {
      const protocol = new URL(String(value)).protocol;
      return protocol === 'http:' || protocol === 'https:';
    } catch (_error) {
      return false;
    }
  }

  function safeUrl(value) {
    if (value === undefined || value === null || value === '') return null;
    const url = String(value);
    if (!supportedUrl(url) || /[\r\n\0]/.test(url) || byteLength(url) > MAX_CONTEXT_BYTES) {
      return null;
    }
    return url;
  }

  function sameResourceUrl(left, right) {
    try {
      const a = new URL(String(left));
      const b = new URL(String(right));
      return a.protocol === b.protocol
        && a.hostname.toLowerCase() === b.hostname.toLowerCase()
        && (a.port || (a.protocol === 'https:' ? '443' : '80'))
          === (b.port || (b.protocol === 'https:' ? '443' : '80'))
        && a.pathname === b.pathname;
    } catch (_error) {
      return false;
    }
  }

  function cloneHeaders(headers) {
    return headers.map((header) => ({ name: header.name, value: header.value }));
  }

  function cloneEntry(entry, download) {
    return {
      headers: cloneHeaders(entry.headers),
      sourcePageUrl: safeUrl(download.referrer) || entry.sourcePageUrl || null,
      initialUrl: entry.initialUrl,
      finalUrl: entry.finalUrl,
      tabId: Number.isInteger(entry.tabId) ? entry.tabId : null,
      incognito: Boolean(download.incognito),
      cookieStoreId: download.cookieStoreId === undefined || download.cookieStoreId === null
        ? null
        : String(download.cookieStoreId),
      capturedUnixMs: entry.capturedUnixMs
    };
  }

  function createRequestContextTracker(options = {}) {
    const now = typeof options.now === 'function' ? options.now : Date.now;
    const ttlMs = Number.isFinite(options.ttlMs) ? Math.max(1, options.ttlMs) : 15_000;
    const maxEntries = Number.isInteger(options.maxEntries) ? Math.max(1, options.maxEntries) : 256;
    const entries = new Map();
    const reauthorizationSessions = new Map();
    let nextSessionId = 1;

    function prune(current = now()) {
      for (const [requestId, entry] of entries) {
        if (current - entry.capturedUnixMs > ttlMs) entries.delete(requestId);
      }
      for (const [sessionId, session] of reauthorizationSessions) {
        if (current - session.startedUnixMs > session.ttlMs) {
          reauthorizationSessions.delete(sessionId);
        }
      }
    }

    function evictOldest() {
      while (entries.size > maxEntries) {
        let oldestId = null;
        let oldestTime = Infinity;
        for (const [requestId, entry] of entries) {
          if (entry.capturedUnixMs < oldestTime) {
            oldestId = requestId;
            oldestTime = entry.capturedUnixMs;
          }
        }
        if (oldestId === null) break;
        entries.delete(oldestId);
      }
    }

    function observeSendHeaders(details = {}) {
      if (String(details.method || '').toUpperCase() !== 'GET') return false;
      if (!supportedUrl(details.url)) return false;
      const requestId = String(details.requestId || '');
      if (!requestId) return false;
      const current = now();
      prune(current);
      let entry = entries.get(requestId);
      if (!entry) {
        entry = {
          initialUrl: String(details.url),
          finalUrl: String(details.url),
          tabId: Number.isInteger(details.tabId) ? details.tabId : null,
          sourcePageUrl: safeUrl(details.documentUrl)
            || safeUrl(details.originUrl)
            || safeUrl(details.initiator)
            || null,
          headers: [],
          capturedUnixMs: current,
          completed: false
        };
        entries.set(requestId, entry);
      } else {
        entry.finalUrl = String(details.url);
        if (Number.isInteger(details.tabId)) entry.tabId = details.tabId;
        entry.sourcePageUrl = entry.sourcePageUrl
          || safeUrl(details.documentUrl)
          || safeUrl(details.originUrl)
          || safeUrl(details.initiator)
          || null;
      }
      entry.headers = filterRequestHeaders(details.requestHeaders);
      evictOldest();
      return true;
    }

    function observeRedirect(details = {}) {
      const requestId = String(details.requestId || '');
      const entry = entries.get(requestId);
      if (!entry || !supportedUrl(details.redirectUrl)) return false;
      entry.finalUrl = String(details.redirectUrl);
      entry.sourcePageUrl = entry.sourcePageUrl
        || safeUrl(details.documentUrl)
        || safeUrl(details.originUrl)
        || safeUrl(details.initiator)
        || null;
      return true;
    }

    function observeComplete(details = {}) {
      const requestId = String(details.requestId || '');
      const entry = entries.get(requestId);
      if (!entry) return false;
      entry.completed = true;
      return true;
    }

    function claimDownload(download = {}) {
      const url = String(download.url || '');
      if (!supportedUrl(url)) return null;
      const current = now();
      prune(current);
      const candidates = [];
      for (const entry of entries.values()) {
        if (entry.initialUrl !== url && entry.finalUrl !== url) continue;
        candidates.push(entry);
      }
      if (candidates.length === 0) return null;

      const referrer = safeUrl(download.referrer);
      const sourceMatches = referrer
        ? candidates.filter((entry) => entry.sourcePageUrl === referrer)
        : [];
      const usable = sourceMatches.length > 0 ? sourceMatches : candidates;
      // Two identical URLs without a matching source page cannot be safely
      // correlated.  Keeping both requests is safer than leaking one tab's
      // Cookie/Authorization into another tab's download.
      if (usable.length !== 1) return null;
      const entry = usable[0];
      let requestId = null;
      for (const [candidateId, candidate] of entries) {
        if (candidate === entry) {
          requestId = candidateId;
          break;
        }
      }
      if (requestId === null) return null;
      entries.delete(requestId);
      return cloneEntry(entry, download);
    }

    function beginReauthorization(criteria = {}) {
      const current = now();
      prune(current);
      const sessionId = String(criteria.sessionId || `reauth-${current}-${nextSessionId++}`);
      const resourceUrls = [criteria.initialUrl, criteria.finalUrl]
        .map(safeUrl)
        .filter(Boolean);
      const sourcePageUrl = safeUrl(criteria.sourcePageUrl);
      reauthorizationSessions.set(sessionId, {
        sessionId,
        startedUnixMs: current,
        ttlMs: Number.isFinite(criteria.ttlMs) ? Math.max(1, criteria.ttlMs) : 5 * 60 * 1000,
        tabId: Number.isInteger(criteria.tabId) ? criteria.tabId : null,
        sourcePageUrl,
        resourceUrls,
        incognito: Boolean(criteria.incognito),
        cookieStoreId: criteria.cookieStoreId === undefined || criteria.cookieStoreId === null
          ? null
          : String(criteria.cookieStoreId)
      });
      return sessionId;
    }

    function claimReauthorization(sessionId) {
      const session = reauthorizationSessions.get(String(sessionId));
      if (!session) return null;
      const current = now();
      if (current - session.startedUnixMs > session.ttlMs) {
        reauthorizationSessions.delete(session.sessionId);
        return null;
      }
      const candidates = [];
      for (const entry of entries.values()) {
        if (entry.capturedUnixMs < session.startedUnixMs) continue;
        if (session.tabId !== null && entry.tabId !== session.tabId) continue;
        if (session.sourcePageUrl && entry.sourcePageUrl
            && !sameResourceUrl(session.sourcePageUrl, entry.sourcePageUrl)) continue;
        if (session.resourceUrls.length > 0
            && !session.resourceUrls.some((url) =>
              sameResourceUrl(url, entry.initialUrl) || sameResourceUrl(url, entry.finalUrl))) {
          continue;
        }
        candidates.push(entry);
      }
      if (candidates.length !== 1) return null;
      const entry = candidates[0];
      let requestId = null;
      for (const [candidateId, candidate] of entries) {
        if (candidate === entry) {
          requestId = candidateId;
          break;
        }
      }
      if (requestId === null) return null;
      entries.delete(requestId);
      reauthorizationSessions.delete(session.sessionId);
      return cloneEntry(entry, {
        referrer: session.sourcePageUrl,
        incognito: session.incognito,
        cookieStoreId: session.cookieStoreId
      });
    }

    function cancelReauthorization(sessionId) {
      return reauthorizationSessions.delete(String(sessionId));
    }

    return {
      observeSendHeaders,
      observeRedirect,
      observeComplete,
      observeError: observeComplete,
      claimDownload,
      beginReauthorization,
      claimReauthorization,
      cancelReauthorization,
      prune,
      size: () => entries.size
    };
  }

  return {
    BLOCKED_HEADERS: Array.from(BLOCKED_HEADERS),
    createRequestContextTracker,
    filterRequestHeaders
  };
});
